### ISSUE TITLE
Export data from bookings table 

### ISSUE THREAD

**Issue by rtnpro** [rtnpro/opencabs#9]
Export data in csv format from bookings table.

**Comment by rahulbajaj0509** [comment]
I am working on this bug :)

**Comment by rtnpro** [comment]
Hey @rahulbajaj0509 I needed the fix for it ASAP. So, I fixed it, for now.

**Comment by rahulbajaj0509** [comment]
Np @rtnpro. sorry for the delay. I am busy with college exams so I was unable to fix the bug :)
